allow-branch = ["main", "development", "!HEAD"]
publish = false
consolidate-commits = true
pre-release-commit-message = "chore: Release {{crate_name}} version {{version}}"
pre-release-hook = ["./launchers/mobile/android/update_version.sh"]
pre-release-replacements = []
tag-message = "chore: Release {{crate_name}} version {{version}}"
tag-name = "v{{version}}"
